### ISSUE TITLE
Unknown Desktop Environment i3

### ISSUE THREAD

**Issue by KevDi** [damonlynch/showinfilemanager#2]
If i currently run the Rapid-Photo-Downloader on my Archlinux System with Python 3.10 i got an error in the `showinfm` Package.
It gives me the following Exception:

```
Traceback (most recent call last):
  File "/home/kev/.local/lib/python3.10/site-packages/showinfm/system/linux.py", line 784, in linux_desktop
    return LinuxDesktop[env]
  File "/usr/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: 'i3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rapid-photo-downloader", line 33, in <module>
    sys.exit(load_entry_point('rapid-photo-downloader==0.9.27', 'gui_scripts', 'rapid-photo-downloader')())
  File "/usr/bin/rapid-photo-downloader", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/raphodo/rapid.py", line 147, in <module>
    from raphodo.folderpreviewmanager import FolderPreviewManager
  File "/usr/lib/python3.10/site-packages/raphodo/folderpreviewmanager.py", line 30, in <module>
    from raphodo.folderspreview import FoldersPreview, DownloadDestination
  File "/usr/lib/python3.10/site-packages/raphodo/folderspreview.py", line 47, in <module>
    import raphodo.generatename as gn
  File "/usr/lib/python3.10/site-packages/raphodo/generatename.py", line 40, in <module>
    from raphodo.preferences import DownloadsTodayTracker
  File "/usr/lib/python3.10/site-packages/raphodo/preferences.py", line 287, in <module>
    class Preferences:
  File "/usr/lib/python3.10/site-packages/raphodo/preferences.py", line 294, in Preferences
    photo_download_folder=platform_photos_directory(),
  File "/usr/lib/python3.10/site-packages/raphodo/storage.py", line 530, in platform_photos_directory
    if linux_desktop() == LinuxDesktop.wsl2:
  File "/home/kev/.local/lib/python3.10/site-packages/showinfm/system/linux.py", line 786, in linux_desktop
    raise Exception("The desktop environment {} is unknown".format(env))
Exception: The desktop environment i3 is unknown
```

**Comment by damonlynch** [comment]
Fixed in 0.9.28. See https://github.com/damonlynch/rapid-photo-downloader/issues/44
